### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by nsdotorg** [apollographql/blog#25]
The page (https://www.apollographql.com/blog/apollo-client/caching/demystifying-cache-normalization/) has a broken link as highlighted in the screenshot below.

![image](https://user-images.githubusercontent.com/50475136/125770438-f1696c80-107d-4f9e-8498-c4bede1f59cc.png)

**Comment by trevorblades** [comment]
Thanks for letting us know! Just fixed this. It now points to https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy
