### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by jcq** [apollographql/blog#3]
## Description
It would be great if the new Apollo blog had RSS support. While moving away from Medium is great, this appears to have resulted in a loss of this important functionality. (At least I wasn't able to find a feed, but perhaps I missed something.)

## Resources
- [Gatsby Docs on Adding RSS Feeds](https://www.gatsbyjs.org/docs/adding-an-rss-feed/)

**Comment by trevorblades** [comment]
Good point! I'll work on adding an RSS feed soon 👍

**Comment by trevorblades** [comment]
Fixed by #5
